<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks Export</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            line-height: 1.4;
            color: #1f2937;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #3b82f6;
        }

        .header h1 {
            font-size: 20px;
            color: #1e40af;
            margin-bottom: 5px;
        }

        .header .meta {
            font-size: 9px;
            color: #6b7280;
        }

        .filters {
            background-color: #f3f4f6;
            padding: 8px 12px;
            margin-bottom: 15px;
            border-radius: 4px;
            font-size: 9px;
        }

        .filters strong {
            color: #374151;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        thead {
            background-color: #3b82f6;
        }

        th {
            color: white;
            padding: 8px 6px;
            text-align: left;
            font-size: 9px;
            font-weight: 600;
        }

        td {
            padding: 6px;
            border-bottom: 1px solid #e5e7eb;
            vertical-align: top;
        }

        tr:nth-child(even) {
            background-color: #f9fafb;
        }

        .task-name {
            font-weight: 600;
            color: #1f2937;
            max-width: 150px;
            word-wrap: break-word;
        }

        .task-description {
            font-size: 8px;
            color: #6b7280;
            max-width: 200px;
            word-wrap: break-word;
        }

        .badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: 600;
        }

        .status-unplanned {
            background-color: #e5e7eb;
            color: #374151;
        }

        .status-pending {
            background-color: #fef3c7;
            color: #92400e;
        }

        .status-in-progress {
            background-color: #dbeafe;
            color: #1e40af;
        }

        .status-done {
            background-color: #d1fae5;
            color: #065f46;
        }

        .priority-low {
            color: #059669;
        }

        .priority-medium {
            color: #d97706;
        }

        .priority-high {
            color: #dc2626;
        }

        .priority-critical {
            color: #7c3aed;
            font-weight: 700;
        }

        .date {
            font-size: 9px;
            white-space: nowrap;
        }

        .overdue {
            color: #dc2626;
            font-weight: 600;
        }

        .footer {
            position: fixed;
            bottom: 20px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 8px;
            color: #9ca3af;
        }

        .summary {
            margin-top: 15px;
            padding: 10px;
            background-color: #eff6ff;
            border-radius: 4px;
        }

        .summary h3 {
            font-size: 11px;
            color: #1e40af;
            margin-bottom: 8px;
        }

        .summary-grid {
            display: table;
            width: 100%;
        }

        .summary-item {
            display: table-cell;
            text-align: center;
            padding: 5px;
        }

        .summary-value {
            font-size: 16px;
            font-weight: 700;
            color: #3b82f6;
        }

        .summary-label {
            font-size: 8px;
            color: #6b7280;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📋 Tasks Export</h1>
        <div class="meta">
            Generated by {{ $user->name }} on {{ $generatedAt->format('F j, Y \a\t g:i A') }}
        </div>
    </div>

    @if(array_filter($filters))
    <div class="filters">
        <strong>Active Filters:</strong>
        @if(!empty($filters['status']))
            Status: {{ $filters['status'] }}
        @endif
        @if(!empty($filters['priority']))
            | Priority: {{ $filters['priority'] }}
        @endif
        @if(!empty($filters['project_id']))
            | Project ID: {{ $filters['project_id'] }}
        @endif
        @if(!empty($filters['search']))
            | Search: "{{ $filters['search'] }}"
        @endif
    </div>
    @endif

    <table>
        <thead>
            <tr>
                <th style="width: 20%;">Task</th>
                <th style="width: 25%;">Description</th>
                <th style="width: 10%;">Status</th>
                <th style="width: 8%;">Priority</th>
                <th style="width: 10%;">Due Date</th>
                <th style="width: 12%;">Project</th>
                <th style="width: 15%;">Assigned To</th>
            </tr>
        </thead>
        <tbody>
            @forelse($tasks as $task)
            <tr>
                <td class="task-name">{{ $task->name }}</td>
                <td class="task-description">{{ Str::limit(strip_tags($task->description ?? ''), 100) }}</td>
                <td>
                    @php
                        $statusClass = match($task->status?->value) {
                            'Unplanned' => 'status-unplanned',
                            'Pending' => 'status-pending',
                            'In-Progress' => 'status-in-progress',
                            'Done' => 'status-done',
                            default => 'status-unplanned',
                        };
                    @endphp
                    <span class="badge {{ $statusClass }}">{{ $task->status?->value ?? 'N/A' }}</span>
                </td>
                <td>
                    @php
                        $priorityClass = match($task->priority?->value) {
                            'Low' => 'priority-low',
                            'Medium' => 'priority-medium',
                            'High' => 'priority-high',
                            'Critical' => 'priority-critical',
                            default => '',
                        };
                    @endphp
                    <span class="{{ $priorityClass }}">{{ $task->priority?->value ?? 'N/A' }}</span>
                </td>
                <td class="date {{ $task->due_date && $task->due_date->isPast() && $task->status?->value !== 'Done' ? 'overdue' : '' }}">
                    {{ $task->due_date?->format('M j, Y') ?? '-' }}
                </td>
                <td>{{ $task->project?->name ?? 'N/A' }}</td>
                <td>{{ $task->assignee?->name ?? 'Unassigned' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" style="text-align: center; padding: 20px; color: #6b7280;">
                    No tasks found matching the criteria.
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    @if($tasks->count() > 0)
    <div class="summary">
        <h3>Summary</h3>
        <div class="summary-grid">
            <div class="summary-item">
                <div class="summary-value">{{ $tasks->count() }}</div>
                <div class="summary-label">Total Tasks</div>
            </div>
            <div class="summary-item">
                <div class="summary-value">{{ $tasks->where('status.value', 'Done')->count() }}</div>
                <div class="summary-label">Completed</div>
            </div>
            <div class="summary-item">
                <div class="summary-value">{{ $tasks->where('status.value', 'In-Progress')->count() }}</div>
                <div class="summary-label">In Progress</div>
            </div>
            <div class="summary-item">
                <div class="summary-value">{{ $tasks->filter(fn($t) => $t->due_date && $t->due_date->isPast() && $t->status?->value !== 'Done')->count() }}</div>
                <div class="summary-label">Overdue</div>
            </div>
        </div>
    </div>
    @endif

    <div class="footer">
        TeamFlow - Team Project Management System | Page 1
    </div>
</body>
</html>
